# Generated by Django 6.0.1 on 2026-01-10 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('basic', 'Basic Coverage'), ('standard', 'Standard Coverage'), ('premium', 'Premium Coverage'), ('none', 'No Insurance')], max_length=20, unique=True, verbose_name='insurance type')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='daily price')),
                ('deductible', models.DecimalField(decimal_places=2, help_text='Amount customer pays in case of damage', max_digits=10, verbose_name='deductible')),
                ('coverage_details', models.TextField(blank=True, help_text='What is covered by this insurance', verbose_name='coverage details')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'insurance option',
                'verbose_name_plural': 'insurance options',
                'ordering': ['daily_price'],
            },
        ),
        migrations.CreateModel(
            name='RentalExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='daily price')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price cap regardless of rental duration', max_digits=10, null=True, verbose_name='maximum price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'rental extra',
                'verbose_name_plural': 'rental extras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(editable=False, max_length=20, unique=True, verbose_name='booking reference')),
                ('customer_name', models.CharField(max_length=200, verbose_name='customer name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='customer email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='customer phone')),
                ('driver_license_number', models.CharField(max_length=50, verbose_name='driver license number')),
                ('driver_license_expiry', models.DateField(verbose_name='driver license expiry')),
                ('driver_date_of_birth', models.DateField(verbose_name='driver date of birth')),
                ('pickup_datetime', models.DateTimeField(verbose_name='pickup date and time')),
                ('return_datetime', models.DateTimeField(verbose_name='return date and time')),
                ('insurance_type', models.CharField(choices=[('basic', 'Basic Coverage'), ('standard', 'Standard Coverage'), ('premium', 'Premium Coverage'), ('none', 'No Insurance')], default='basic', max_length=20, verbose_name='insurance type')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='daily rate')),
                ('total_days', models.PositiveSmallIntegerField(verbose_name='total days')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='insurance cost')),
                ('extras_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='extras cost')),
                ('different_location_fee', models.DecimalField(decimal_places=2, default=0, help_text='Fee for returning at different location', max_digits=10, verbose_name='different location fee')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='security deposit')),
                ('currency', models.CharField(default='MAD', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('special_requests', models.TextField(blank=True, verbose_name='special requests')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('actual_pickup_datetime', models.DateTimeField(blank=True, null=True, verbose_name='actual pickup time')),
                ('actual_return_datetime', models.DateTimeField(blank=True, null=True, verbose_name='actual return time')),
                ('pickup_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='pickup mileage')),
                ('return_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='return mileage')),
                ('fuel_level_pickup', models.CharField(blank=True, max_length=20, verbose_name='fuel level at pickup')),
                ('fuel_level_return', models.CharField(blank=True, max_length=20, verbose_name='fuel level at return')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_pickups', to='locations.location', verbose_name='pickup location')),
                ('return_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_returns', to='locations.location', verbose_name='return location')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='vehicles.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'rental',
                'verbose_name_plural': 'rentals',
                'ordering': ['-pickup_datetime'],
            },
        ),
        migrations.CreateModel(
            name='RentalExtraBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rentals.rentalextra', verbose_name='extra')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_extras', to='rentals.rental', verbose_name='rental')),
            ],
            options={
                'verbose_name': 'booked extra',
                'verbose_name_plural': 'booked extras',
            },
        ),
    ]
