# Generated by Django 6.0.1 on 2026-01-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='pickup_location',
            field=models.CharField(help_text='Pickup location name or address', max_length=200, verbose_name='pickup location'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_location',
            field=models.CharField(help_text='Return location name or address', max_length=200, verbose_name='return location'),
        ),
    ]
