# Generated by Django 6.0.1 on 2026-01-10 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_fr', models.TextField(null=True, verbose_name='description')),
                ('description_ar', models.TextField(null=True, verbose_name='description')),
                ('description_es', models.TextField(null=True, verbose_name='description')),
                ('short_description', models.CharField(max_length=300, verbose_name='short description')),
                ('short_description_en', models.CharField(max_length=300, null=True, verbose_name='short description')),
                ('short_description_fr', models.CharField(max_length=300, null=True, verbose_name='short description')),
                ('short_description_ar', models.CharField(max_length=300, null=True, verbose_name='short description')),
                ('short_description_es', models.CharField(max_length=300, null=True, verbose_name='short description')),
                ('trip_type', models.CharField(choices=[('day_trip', 'Day Trip'), ('multi_day', 'Multi-Day Tour'), ('half_day', 'Half-Day Trip'), ('private', 'Private Tour'), ('group', 'Group Tour')], default='day_trip', max_length=20, verbose_name='trip type')),
                ('duration_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='duration (hours)')),
                ('duration_days', models.PositiveSmallIntegerField(default=1, verbose_name='duration (days)')),
                ('min_participants', models.PositiveSmallIntegerField(default=1, verbose_name='minimum participants')),
                ('max_participants', models.PositiveSmallIntegerField(default=20, verbose_name='maximum participants')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price per person')),
                ('child_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for children under 12', max_digits=10, null=True, verbose_name='child price')),
                ('private_tour_price', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price for private tour', max_digits=10, null=True, verbose_name='private tour price')),
                ('currency', models.CharField(default='MAD', max_length=3, verbose_name='currency')),
                ('inclusions', models.TextField(blank=True, help_text='What is included in the trip (one item per line)', verbose_name='inclusions')),
                ('inclusions_en', models.TextField(blank=True, help_text='What is included in the trip (one item per line)', null=True, verbose_name='inclusions')),
                ('inclusions_fr', models.TextField(blank=True, help_text='What is included in the trip (one item per line)', null=True, verbose_name='inclusions')),
                ('inclusions_ar', models.TextField(blank=True, help_text='What is included in the trip (one item per line)', null=True, verbose_name='inclusions')),
                ('inclusions_es', models.TextField(blank=True, help_text='What is included in the trip (one item per line)', null=True, verbose_name='inclusions')),
                ('exclusions', models.TextField(blank=True, help_text='What is not included (one item per line)', verbose_name='exclusions')),
                ('exclusions_en', models.TextField(blank=True, help_text='What is not included (one item per line)', null=True, verbose_name='exclusions')),
                ('exclusions_fr', models.TextField(blank=True, help_text='What is not included (one item per line)', null=True, verbose_name='exclusions')),
                ('exclusions_ar', models.TextField(blank=True, help_text='What is not included (one item per line)', null=True, verbose_name='exclusions')),
                ('exclusions_es', models.TextField(blank=True, help_text='What is not included (one item per line)', null=True, verbose_name='exclusions')),
                ('itinerary', models.TextField(blank=True, help_text='Detailed itinerary of the trip', verbose_name='itinerary')),
                ('itinerary_en', models.TextField(blank=True, help_text='Detailed itinerary of the trip', null=True, verbose_name='itinerary')),
                ('itinerary_fr', models.TextField(blank=True, help_text='Detailed itinerary of the trip', null=True, verbose_name='itinerary')),
                ('itinerary_ar', models.TextField(blank=True, help_text='Detailed itinerary of the trip', null=True, verbose_name='itinerary')),
                ('itinerary_es', models.TextField(blank=True, help_text='Detailed itinerary of the trip', null=True, verbose_name='itinerary')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='trips/', verbose_name='featured image')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('departure_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_departing', to='locations.location', verbose_name='departure location')),
                ('destinations', models.ManyToManyField(related_name='trips_visiting', to='locations.location', verbose_name='destinations')),
            ],
            options={
                'verbose_name': 'trip',
                'verbose_name_plural': 'trips',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trips/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trips.trip', verbose_name='trip')),
            ],
            options={
                'verbose_name': 'trip image',
                'verbose_name_plural': 'trip images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TripSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_date', models.DateField(blank=True, help_text='Leave blank for recurring schedule', null=True, verbose_name='specific date')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True, verbose_name='day of week')),
                ('departure_time', models.TimeField(verbose_name='departure time')),
                ('available_spots', models.PositiveSmallIntegerField(verbose_name='available spots')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trips.trip', verbose_name='trip')),
            ],
            options={
                'verbose_name': 'trip schedule',
                'verbose_name_plural': 'trip schedules',
                'ordering': ['specific_date', 'day_of_week', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='TripBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(editable=False, max_length=20, unique=True, verbose_name='booking reference')),
                ('trip_date', models.DateField(verbose_name='trip date')),
                ('customer_name', models.CharField(max_length=200, verbose_name='customer name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='customer email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='customer phone')),
                ('adults', models.PositiveSmallIntegerField(default=1, verbose_name='adults')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='children')),
                ('pickup_address', models.TextField(blank=True, verbose_name='pickup address')),
                ('is_private', models.BooleanField(default=False, verbose_name='private tour')),
                ('price_per_adult', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price per adult')),
                ('price_per_child', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price per child')),
                ('extras_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='extras price')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price')),
                ('currency', models.CharField(default='MAD', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=20, verbose_name='status')),
                ('special_requests', models.TextField(blank=True, verbose_name='special requests')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_bookings', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('pickup_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='pickup location')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='trips.trip', verbose_name='trip')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='trips.tripschedule', verbose_name='schedule')),
            ],
            options={
                'verbose_name': 'trip booking',
                'verbose_name_plural': 'trip bookings',
                'ordering': ['-trip_date', '-created_at'],
            },
        ),
    ]
