# Generated by Django 6.0.1 on 2026-01-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripbooking',
            name='pickup_location',
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_location',
            field=models.CharField(blank=True, default='', help_text='City or place name where the trip starts', max_length=200, verbose_name='departure location'),
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destinations',
        ),
        migrations.AddField(
            model_name='trip',
            name='destinations',
            field=models.TextField(blank=True, default='', help_text='Places visited during the trip (one per line)', verbose_name='destinations'),
        ),
    ]
