# Generated by Django 5.0.1 on 2026-01-28 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_tripbooking_pickup_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='accessibility_info',
            field=models.TextField(blank=True, help_text='Information about wheelchair access, mobility requirements, etc.', verbose_name='accessibility info'),
        ),
        migrations.AddField(
            model_name='trip',
            name='booking_notice_hours',
            field=models.PositiveIntegerField(default=24, help_text='Minimum hours in advance required to book', verbose_name='booking notice (hours)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='cancellation_policy',
            field=models.CharField(choices=[('flexible', 'Flexible - Full refund up to 24h before'), ('moderate', 'Moderate - Full refund up to 48h before'), ('strict', 'Strict - 50% refund up to 7 days before'), ('non_refundable', 'Non-refundable')], default='flexible', max_length=20, verbose_name='cancellation policy'),
        ),
        migrations.AddField(
            model_name='trip',
            name='child_policy',
            field=models.TextField(blank=True, help_text='Policy regarding children and age restrictions', verbose_name='child policy'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_languages',
            field=models.CharField(blank=True, help_text='Comma-separated language codes (e.g., en,fr,ar,es)', max_length=500, verbose_name='driver languages'),
        ),
        migrations.AddField(
            model_name='trip',
            name='instant_confirmation',
            field=models.BooleanField(default=True, verbose_name='instant confirmation'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 160 characters)', max_length=160, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, verbose_name='meta keywords'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 70 characters)', max_length=70, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='trip',
            name='pricing_model',
            field=models.CharField(choices=[('per_person', 'Per Person'), ('per_group', 'Per Group (Flat Rate)'), ('tiered', 'Tiered Pricing')], default='per_person', max_length=20, verbose_name='pricing model'),
        ),
        migrations.AddField(
            model_name='trip',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publish date'),
        ),
        migrations.AddField(
            model_name='trip',
            name='related_trips',
            field=models.ManyToManyField(blank=True, to='trips.trip', verbose_name='related tours'),
        ),
        migrations.AddField(
            model_name='trip',
            name='service_type',
            field=models.CharField(choices=[('tour', 'Guided Tour'), ('transfer', 'Transfer Service'), ('excursion', 'Day Excursion'), ('activity', 'Activity')], default='tour', max_length=20, verbose_name='service type'),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='alt text'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='is_thumbnail',
            field=models.BooleanField(default=False, verbose_name='use as thumbnail'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price per person'),
        ),
        migrations.CreateModel(
            name='TripContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='trips.trip', verbose_name='trip')),
            ],
            options={
                'verbose_name': 'content block',
                'verbose_name_plural': 'content blocks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TripFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='trips.trip', verbose_name='trip')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TripHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi-check-circle', help_text='Bootstrap icon class (e.g., bi-check-circle)', max_length=50, verbose_name='icon')),
                ('text', models.CharField(max_length=200, verbose_name='highlight text')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='trips.trip', verbose_name='trip')),
            ],
            options={
                'verbose_name': 'trip highlight',
                'verbose_name_plural': 'trip highlights',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TripItineraryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('start', 'Start Point'), ('stop', 'Stop'), ('end', 'End Point')], default='stop', max_length=10, verbose_name='stop type')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (minutes)')),
                ('has_admission', models.BooleanField(default=False, help_text='Check if admission fee is included', verbose_name='admission included')),
                ('pickup_flexibility', models.BooleanField(default=False, help_text='Allow custom pickup location', verbose_name='flexible pickup')),
                ('same_as_start', models.BooleanField(default=False, help_text='End point is the same as start point', verbose_name='same as start')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trips/itinerary/', verbose_name='image')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_stops', to='trips.trip', verbose_name='trip')),
            ],
            options={
                'verbose_name': 'itinerary stop',
                'verbose_name_plural': 'itinerary stops',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TripPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "1-2 persons", "3-5 persons"', max_length=100, verbose_name='tier name')),
                ('min_travelers', models.PositiveSmallIntegerField(default=1, verbose_name='minimum travelers')),
                ('max_travelers', models.PositiveSmallIntegerField(default=2, verbose_name='maximum travelers')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price per person')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated or override', max_digits=10, null=True, verbose_name='total price')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='trips.trip', verbose_name='trip')),
            ],
            options={
                'verbose_name': 'price tier',
                'verbose_name_plural': 'price tiers',
                'ordering': ['order', 'min_travelers'],
            },
        ),
    ]
