# Generated by Django 5.0.1 on 2026-02-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_tour_form_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='accessibility_info_ar',
            field=models.TextField(blank=True, help_text='Information about wheelchair access, mobility requirements, etc.', null=True, verbose_name='accessibility info'),
        ),
        migrations.AddField(
            model_name='trip',
            name='accessibility_info_de',
            field=models.TextField(blank=True, help_text='Information about wheelchair access, mobility requirements, etc.', null=True, verbose_name='accessibility info'),
        ),
        migrations.AddField(
            model_name='trip',
            name='accessibility_info_en',
            field=models.TextField(blank=True, help_text='Information about wheelchair access, mobility requirements, etc.', null=True, verbose_name='accessibility info'),
        ),
        migrations.AddField(
            model_name='trip',
            name='accessibility_info_es',
            field=models.TextField(blank=True, help_text='Information about wheelchair access, mobility requirements, etc.', null=True, verbose_name='accessibility info'),
        ),
        migrations.AddField(
            model_name='trip',
            name='accessibility_info_fr',
            field=models.TextField(blank=True, help_text='Information about wheelchair access, mobility requirements, etc.', null=True, verbose_name='accessibility info'),
        ),
        migrations.AddField(
            model_name='trip',
            name='accessibility_info_it',
            field=models.TextField(blank=True, help_text='Information about wheelchair access, mobility requirements, etc.', null=True, verbose_name='accessibility info'),
        ),
        migrations.AddField(
            model_name='trip',
            name='accessibility_info_pt',
            field=models.TextField(blank=True, help_text='Information about wheelchair access, mobility requirements, etc.', null=True, verbose_name='accessibility info'),
        ),
        migrations.AddField(
            model_name='trip',
            name='child_policy_ar',
            field=models.TextField(blank=True, help_text='Policy regarding children and age restrictions', null=True, verbose_name='child policy'),
        ),
        migrations.AddField(
            model_name='trip',
            name='child_policy_de',
            field=models.TextField(blank=True, help_text='Policy regarding children and age restrictions', null=True, verbose_name='child policy'),
        ),
        migrations.AddField(
            model_name='trip',
            name='child_policy_en',
            field=models.TextField(blank=True, help_text='Policy regarding children and age restrictions', null=True, verbose_name='child policy'),
        ),
        migrations.AddField(
            model_name='trip',
            name='child_policy_es',
            field=models.TextField(blank=True, help_text='Policy regarding children and age restrictions', null=True, verbose_name='child policy'),
        ),
        migrations.AddField(
            model_name='trip',
            name='child_policy_fr',
            field=models.TextField(blank=True, help_text='Policy regarding children and age restrictions', null=True, verbose_name='child policy'),
        ),
        migrations.AddField(
            model_name='trip',
            name='child_policy_it',
            field=models.TextField(blank=True, help_text='Policy regarding children and age restrictions', null=True, verbose_name='child policy'),
        ),
        migrations.AddField(
            model_name='trip',
            name='child_policy_pt',
            field=models.TextField(blank=True, help_text='Policy regarding children and age restrictions', null=True, verbose_name='child policy'),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_location_ar',
            field=models.CharField(blank=True, default='', help_text='City or place name where the trip starts', max_length=200, null=True, verbose_name='departure location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_location_de',
            field=models.CharField(blank=True, default='', help_text='City or place name where the trip starts', max_length=200, null=True, verbose_name='departure location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_location_en',
            field=models.CharField(blank=True, default='', help_text='City or place name where the trip starts', max_length=200, null=True, verbose_name='departure location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_location_es',
            field=models.CharField(blank=True, default='', help_text='City or place name where the trip starts', max_length=200, null=True, verbose_name='departure location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_location_fr',
            field=models.CharField(blank=True, default='', help_text='City or place name where the trip starts', max_length=200, null=True, verbose_name='departure location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_location_it',
            field=models.CharField(blank=True, default='', help_text='City or place name where the trip starts', max_length=200, null=True, verbose_name='departure location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_location_pt',
            field=models.CharField(blank=True, default='', help_text='City or place name where the trip starts', max_length=200, null=True, verbose_name='departure location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='description_de',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='trip',
            name='description_it',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='trip',
            name='description_pt',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='trip',
            name='destinations_ar',
            field=models.TextField(blank=True, default='', help_text='Places visited during the trip (one per line)', null=True, verbose_name='destinations'),
        ),
        migrations.AddField(
            model_name='trip',
            name='destinations_de',
            field=models.TextField(blank=True, default='', help_text='Places visited during the trip (one per line)', null=True, verbose_name='destinations'),
        ),
        migrations.AddField(
            model_name='trip',
            name='destinations_en',
            field=models.TextField(blank=True, default='', help_text='Places visited during the trip (one per line)', null=True, verbose_name='destinations'),
        ),
        migrations.AddField(
            model_name='trip',
            name='destinations_es',
            field=models.TextField(blank=True, default='', help_text='Places visited during the trip (one per line)', null=True, verbose_name='destinations'),
        ),
        migrations.AddField(
            model_name='trip',
            name='destinations_fr',
            field=models.TextField(blank=True, default='', help_text='Places visited during the trip (one per line)', null=True, verbose_name='destinations'),
        ),
        migrations.AddField(
            model_name='trip',
            name='destinations_it',
            field=models.TextField(blank=True, default='', help_text='Places visited during the trip (one per line)', null=True, verbose_name='destinations'),
        ),
        migrations.AddField(
            model_name='trip',
            name='destinations_pt',
            field=models.TextField(blank=True, default='', help_text='Places visited during the trip (one per line)', null=True, verbose_name='destinations'),
        ),
        migrations.AddField(
            model_name='trip',
            name='exclusions_de',
            field=models.TextField(blank=True, help_text='What is not included (one item per line)', null=True, verbose_name='exclusions'),
        ),
        migrations.AddField(
            model_name='trip',
            name='exclusions_it',
            field=models.TextField(blank=True, help_text='What is not included (one item per line)', null=True, verbose_name='exclusions'),
        ),
        migrations.AddField(
            model_name='trip',
            name='exclusions_pt',
            field=models.TextField(blank=True, help_text='What is not included (one item per line)', null=True, verbose_name='exclusions'),
        ),
        migrations.AddField(
            model_name='trip',
            name='inclusions_de',
            field=models.TextField(blank=True, help_text='What is included in the trip (one item per line)', null=True, verbose_name='inclusions'),
        ),
        migrations.AddField(
            model_name='trip',
            name='inclusions_it',
            field=models.TextField(blank=True, help_text='What is included in the trip (one item per line)', null=True, verbose_name='inclusions'),
        ),
        migrations.AddField(
            model_name='trip',
            name='inclusions_pt',
            field=models.TextField(blank=True, help_text='What is included in the trip (one item per line)', null=True, verbose_name='inclusions'),
        ),
        migrations.AddField(
            model_name='trip',
            name='itinerary_de',
            field=models.TextField(blank=True, help_text='Detailed itinerary of the trip', null=True, verbose_name='itinerary'),
        ),
        migrations.AddField(
            model_name='trip',
            name='itinerary_it',
            field=models.TextField(blank=True, help_text='Detailed itinerary of the trip', null=True, verbose_name='itinerary'),
        ),
        migrations.AddField(
            model_name='trip',
            name='itinerary_pt',
            field=models.TextField(blank=True, help_text='Detailed itinerary of the trip', null=True, verbose_name='itinerary'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_description_ar',
            field=models.CharField(blank=True, help_text='SEO description (max 160 characters)', max_length=160, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_description_de',
            field=models.CharField(blank=True, help_text='SEO description (max 160 characters)', max_length=160, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='SEO description (max 160 characters)', max_length=160, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_description_es',
            field=models.CharField(blank=True, help_text='SEO description (max 160 characters)', max_length=160, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_description_fr',
            field=models.CharField(blank=True, help_text='SEO description (max 160 characters)', max_length=160, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_description_it',
            field=models.CharField(blank=True, help_text='SEO description (max 160 characters)', max_length=160, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_description_pt',
            field=models.CharField(blank=True, help_text='SEO description (max 160 characters)', max_length=160, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_title_ar',
            field=models.CharField(blank=True, help_text='SEO title (max 70 characters)', max_length=70, null=True, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_title_de',
            field=models.CharField(blank=True, help_text='SEO title (max 70 characters)', max_length=70, null=True, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='SEO title (max 70 characters)', max_length=70, null=True, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_title_es',
            field=models.CharField(blank=True, help_text='SEO title (max 70 characters)', max_length=70, null=True, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_title_fr',
            field=models.CharField(blank=True, help_text='SEO title (max 70 characters)', max_length=70, null=True, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_title_it',
            field=models.CharField(blank=True, help_text='SEO title (max 70 characters)', max_length=70, null=True, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meta_title_pt',
            field=models.CharField(blank=True, help_text='SEO title (max 70 characters)', max_length=70, null=True, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='trip',
            name='name_de',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='trip',
            name='name_it',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='trip',
            name='name_pt',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='trip',
            name='short_description_de',
            field=models.CharField(max_length=300, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='trip',
            name='short_description_it',
            field=models.CharField(max_length=300, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='trip',
            name='short_description_pt',
            field=models.CharField(max_length=300, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='tripcontentblock',
            name='content_ar',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='tripcontentblock',
            name='content_de',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='tripcontentblock',
            name='content_en',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='tripcontentblock',
            name='content_es',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='tripcontentblock',
            name='content_fr',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='tripcontentblock',
            name='content_it',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='tripcontentblock',
            name='content_pt',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='tripcontentblock',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tripcontentblock',
            name='title_de',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tripcontentblock',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tripcontentblock',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tripcontentblock',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tripcontentblock',
            name='title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tripcontentblock',
            name='title_pt',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tripfaq',
            name='answer_ar',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='tripfaq',
            name='answer_de',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='tripfaq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='tripfaq',
            name='answer_es',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='tripfaq',
            name='answer_fr',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='tripfaq',
            name='answer_it',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='tripfaq',
            name='answer_pt',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='tripfaq',
            name='question_ar',
            field=models.CharField(max_length=300, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='tripfaq',
            name='question_de',
            field=models.CharField(max_length=300, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='tripfaq',
            name='question_en',
            field=models.CharField(max_length=300, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='tripfaq',
            name='question_es',
            field=models.CharField(max_length=300, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='tripfaq',
            name='question_fr',
            field=models.CharField(max_length=300, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='tripfaq',
            name='question_it',
            field=models.CharField(max_length=300, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='tripfaq',
            name='question_pt',
            field=models.CharField(max_length=300, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='triphighlight',
            name='text_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='highlight text'),
        ),
        migrations.AddField(
            model_name='triphighlight',
            name='text_de',
            field=models.CharField(max_length=200, null=True, verbose_name='highlight text'),
        ),
        migrations.AddField(
            model_name='triphighlight',
            name='text_en',
            field=models.CharField(max_length=200, null=True, verbose_name='highlight text'),
        ),
        migrations.AddField(
            model_name='triphighlight',
            name='text_es',
            field=models.CharField(max_length=200, null=True, verbose_name='highlight text'),
        ),
        migrations.AddField(
            model_name='triphighlight',
            name='text_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='highlight text'),
        ),
        migrations.AddField(
            model_name='triphighlight',
            name='text_it',
            field=models.CharField(max_length=200, null=True, verbose_name='highlight text'),
        ),
        migrations.AddField(
            model_name='triphighlight',
            name='text_pt',
            field=models.CharField(max_length=200, null=True, verbose_name='highlight text'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='alt_text_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='alt text'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='alt_text_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='alt text'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='alt text'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='alt_text_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='alt text'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='alt_text_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='alt text'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='alt_text_it',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='alt text'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='alt_text_pt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='alt text'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='caption_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='caption_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='caption_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='caption_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='caption_it',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='caption_pt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='description_pt',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='location_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='location_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='location_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='location_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='location_it',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='location_pt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='name_de',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='name_es',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='name_it',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='tripitinerarystop',
            name='name_pt',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='trippricetier',
            name='name_ar',
            field=models.CharField(help_text='e.g., "1-2 persons", "3-5 persons"', max_length=100, null=True, verbose_name='tier name'),
        ),
        migrations.AddField(
            model_name='trippricetier',
            name='name_de',
            field=models.CharField(help_text='e.g., "1-2 persons", "3-5 persons"', max_length=100, null=True, verbose_name='tier name'),
        ),
        migrations.AddField(
            model_name='trippricetier',
            name='name_en',
            field=models.CharField(help_text='e.g., "1-2 persons", "3-5 persons"', max_length=100, null=True, verbose_name='tier name'),
        ),
        migrations.AddField(
            model_name='trippricetier',
            name='name_es',
            field=models.CharField(help_text='e.g., "1-2 persons", "3-5 persons"', max_length=100, null=True, verbose_name='tier name'),
        ),
        migrations.AddField(
            model_name='trippricetier',
            name='name_fr',
            field=models.CharField(help_text='e.g., "1-2 persons", "3-5 persons"', max_length=100, null=True, verbose_name='tier name'),
        ),
        migrations.AddField(
            model_name='trippricetier',
            name='name_it',
            field=models.CharField(help_text='e.g., "1-2 persons", "3-5 persons"', max_length=100, null=True, verbose_name='tier name'),
        ),
        migrations.AddField(
            model_name='trippricetier',
            name='name_pt',
            field=models.CharField(help_text='e.g., "1-2 persons", "3-5 persons"', max_length=100, null=True, verbose_name='tier name'),
        ),
    ]
