# Generated by Django 5.0.1 on 2026-03-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_tripbooking_custom_field_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='custom data'),
        ),
    ]
