# Generated by Django 5.0.1 on 2026-03-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_add_custom_data_to_trip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trippricetier',
            options={'ordering': ['order', 'min_persons'], 'verbose_name': 'price tier', 'verbose_name_plural': 'price tiers'},
        ),
        migrations.RemoveField(
            model_name='trippricetier',
            name='max_travelers',
        ),
        migrations.RemoveField(
            model_name='trippricetier',
            name='min_travelers',
        ),
        migrations.RemoveField(
            model_name='trippricetier',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trippricetier',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='trippricetier',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='trippricetier',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='trippricetier',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='trippricetier',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='trippricetier',
            name='name_it',
        ),
        migrations.RemoveField(
            model_name='trippricetier',
            name='name_pt',
        ),
        migrations.RemoveField(
            model_name='trippricetier',
            name='price_per_person',
        ),
        migrations.RemoveField(
            model_name='trippricetier',
            name='total_price',
        ),
        migrations.AddField(
            model_name='trippricetier',
            name='max_persons',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='maximum persons'),
        ),
        migrations.AddField(
            model_name='trippricetier',
            name='min_persons',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='minimum persons'),
        ),
        migrations.AddField(
            model_name='trippricetier',
            name='private_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='private price per person'),
        ),
        migrations.AddField(
            model_name='trippricetier',
            name='shared_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='shared price per person'),
        ),
    ]
