# Generated by Django 5.0.1 on 2026-01-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cost_currency',
            field=models.CharField(default='MAD', help_text='Currency for supplier costs', max_length=3, verbose_name='Cost Currency'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_currency',
            field=models.CharField(default='MAD', help_text='Currency for customer prices', max_length=3, verbose_name='Default Currency'),
        ),
    ]
