# Generated by Django 5.0.1 on 2026-01-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_cost_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, help_text='Public key for Stripe (starts with pk_)', max_length=255, verbose_name='Stripe Publishable Key'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_secret_key',
            field=models.CharField(blank=True, help_text='Secret key for Stripe (starts with sk_)', max_length=255, verbose_name='Stripe Secret Key'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, help_text='Webhook signing secret for verifying Stripe events (starts with whsec_)', max_length=255, verbose_name='Stripe Webhook Secret'),
        ),
    ]
