# Generated by Django 5.0.1 on 2026-02-15 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_stripe_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_client_id',
            field=models.CharField(blank=True, help_text='PayPal REST API Client ID', max_length=255, verbose_name='PayPal Client ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_client_secret',
            field=models.CharField(blank=True, help_text='PayPal REST API Client Secret', max_length=255, verbose_name='PayPal Client Secret'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paypal_mode',
            field=models.CharField(default='sandbox', help_text='sandbox or live', max_length=10, verbose_name='PayPal Mode'),
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "WordPress Plugin"', max_length=100, verbose_name='name')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='key hash')),
                ('prefix', models.CharField(help_text='First 8 chars for display', max_length=8, verbose_name='prefix')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20, verbose_name='tier')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('allowed_origins', models.JSONField(blank=True, default=list, help_text='List of allowed CORS origins for this key', verbose_name='allowed origins')),
                ('rate_limit', models.PositiveIntegerField(default=100, help_text='Maximum requests per minute', verbose_name='rate limit')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
