# Generated by Django 5.0.1 on 2026-03-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sitesettings_contact_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Internal identifier (auto-generated from label).', max_length=100, unique=True, verbose_name='field name')),
                ('label', models.CharField(help_text='Label shown to the customer on the booking form', max_length=200, verbose_name='label')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('select', 'Dropdown Select'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('phone', 'Phone')], default='text', max_length=20, verbose_name='field type')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='placeholder')),
                ('help_text_field', models.CharField(blank=True, help_text='Small helper text shown below the field', max_length=300, verbose_name='help text')),
                ('options', models.JSONField(blank=True, default=list, help_text='For select fields: list of option strings', verbose_name='options')),
                ('is_required', models.BooleanField(default=False, verbose_name='required')),
                ('applies_to', models.CharField(choices=[('transfer', 'Transfer Bookings Only'), ('trip', 'Tour Bookings Only'), ('both', 'Both Transfers & Tours')], default='both', max_length=10, verbose_name='applies to')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'custom field',
                'verbose_name_plural': 'custom fields',
                'ordering': ['display_order', 'label'],
            },
        ),
    ]
