# Generated by Django 6.0.1 on 2026-01-10 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('is_per_item', models.BooleanField(default=False, help_text='If checked, price is multiplied by quantity', verbose_name='price per item')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'transfer extra',
                'verbose_name_plural': 'transfer extras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(editable=False, max_length=20, unique=True, verbose_name='booking reference')),
                ('customer_name', models.CharField(max_length=200, verbose_name='customer name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='customer email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='customer phone')),
                ('transfer_type', models.CharField(choices=[('airport_pickup', 'Airport Pickup'), ('airport_dropoff', 'Airport Drop-off'), ('city_to_city', 'City to City'), ('port_transfer', 'Port Transfer'), ('custom', 'Custom Transfer')], default='custom', max_length=20, verbose_name='transfer type')),
                ('pickup_address', models.TextField(blank=True, help_text='Additional address details (hotel name, room number, etc.)', verbose_name='pickup address details')),
                ('dropoff_address', models.TextField(blank=True, verbose_name='drop-off address details')),
                ('pickup_datetime', models.DateTimeField(verbose_name='pickup date and time')),
                ('flight_number', models.CharField(blank=True, max_length=20, verbose_name='flight number')),
                ('flight_arrival_time', models.TimeField(blank=True, null=True, verbose_name='flight arrival time')),
                ('passengers', models.PositiveSmallIntegerField(default=1, verbose_name='number of passengers')),
                ('luggage', models.PositiveSmallIntegerField(default=1, verbose_name='number of luggage')),
                ('child_seats', models.PositiveSmallIntegerField(default=0, verbose_name='child seats required')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base price')),
                ('extras_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='extras price')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price')),
                ('currency', models.CharField(default='MAD', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('assigned', 'Driver Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20, verbose_name='status')),
                ('special_requests', models.TextField(blank=True, verbose_name='special requests')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('is_round_trip', models.BooleanField(default=False, verbose_name='round trip')),
                ('return_datetime', models.DateTimeField(blank=True, null=True, verbose_name='return date and time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_transfers', to=settings.AUTH_USER_MODEL, verbose_name='assigned driver')),
                ('dropoff_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='locations.location', verbose_name='drop-off location')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='locations.location', verbose_name='pickup location')),
                ('return_transfer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_transfer', to='transfers.transfer', verbose_name='return transfer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='vehicles.vehicle', verbose_name='assigned vehicle')),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='vehicles.vehiclecategory', verbose_name='vehicle category')),
            ],
            options={
                'verbose_name': 'transfer',
                'verbose_name_plural': 'transfers',
                'ordering': ['-pickup_datetime'],
            },
        ),
        migrations.CreateModel(
            name='TransferExtraBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='transfers.transferextra', verbose_name='extra')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_extras', to='transfers.transfer', verbose_name='transfer')),
            ],
            options={
                'verbose_name': 'booked extra',
                'verbose_name_plural': 'booked extras',
            },
        ),
    ]
