# Generated by Django 6.0.1 on 2026-01-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='transfer',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='distance (km)'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='dropoff_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='drop-off latitude'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='dropoff_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='drop-off longitude'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estimated duration (minutes)'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='pickup latitude'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='pickup longitude'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='dropoff_address',
            field=models.TextField(help_text='Full drop-off address', verbose_name='drop-off address'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='pickup_address',
            field=models.TextField(help_text='Full pickup address', verbose_name='pickup address'),
        ),
    ]
