# Generated by Django 6.0.1 on 2026-02-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_remove_transfer_dropoff_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deposit amount based on zone/route percentage', max_digits=10, verbose_name='deposit amount'),
        ),
    ]
