# Generated by Django 6.0.1 on 2026-02-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_transfer_deposit_amount'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferextra',
            name='vehicle_categories',
            field=models.ManyToManyField(
                blank=True,
                help_text='Categories this extra is available for. Empty = available for all.',
                related_name='extras',
                to='vehicles.vehiclecategory',
            ),
        ),
    ]
