# Generated by Django 5.0.1 on 2026-03-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_transferextra_vehicle_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='custom_field_values',
            field=models.JSONField(blank=True, default=dict, help_text='Values submitted for admin-defined custom fields', verbose_name='custom field values'),
        ),
    ]
