# Generated by Django 6.0.1 on 2026-01-10 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('gateway_type', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash on Delivery')], max_length=20, unique=True, verbose_name='gateway type')),
                ('display_name', models.CharField(max_length=100, verbose_name='display name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_test_mode', models.BooleanField(default=True, verbose_name='test mode')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Gateway-specific configuration', verbose_name='configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'payment gateway',
                'verbose_name_plural': 'payment gateways',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ref', models.CharField(editable=False, max_length=30, unique=True, verbose_name='payment reference')),
                ('object_id', models.PositiveIntegerField(verbose_name='booking id')),
                ('payment_type', models.CharField(choices=[('transfer', 'Transfer Booking'), ('trip', 'Trip Booking'), ('rental', 'Car Rental')], max_length=20, verbose_name='payment type')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='customer email')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='MAD', max_length=3, verbose_name='currency')),
                ('gateway_payment_id', models.CharField(blank=True, help_text='Payment ID from the gateway (e.g., Stripe PaymentIntent ID)', max_length=255, verbose_name='gateway payment ID')),
                ('gateway_customer_id', models.CharField(blank=True, max_length=255, verbose_name='gateway customer ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='refunded amount')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='booking type')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentgateway', verbose_name='payment gateway')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='invoice number')),
                ('customer_name', models.CharField(max_length=200, verbose_name='customer name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='customer email')),
                ('customer_address', models.TextField(blank=True, verbose_name='customer address')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='tax rate')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tax amount')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('currency', models.CharField(default='MAD', max_length=3, verbose_name='currency')),
                ('line_items', models.JSONField(blank=True, default=list, verbose_name='line items')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='PDF file')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='issue date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='paid date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='payments.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_ref', models.CharField(editable=False, max_length=30, unique=True, verbose_name='refund reference')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('gateway_refund_id', models.CharField(blank=True, max_length=255, verbose_name='gateway refund ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='payment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='processed by')),
            ],
            options={
                'verbose_name': 'refund',
                'verbose_name_plural': 'refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_payment_id'], name='payments_pa_gateway_9ebf66_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
    ]
