# Generated by Django 5.0.1 on 2026-02-15 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='discount value')),
                ('currency', models.CharField(default='MAD', max_length=3, verbose_name='currency')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='minimum order amount')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maximum discount amount')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='usage limit')),
                ('usage_per_customer', models.PositiveIntegerField(blank=True, null=True, verbose_name='usage per customer')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='used count')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='valid until')),
                ('applicable_to', models.CharField(choices=[('all', 'All Bookings'), ('transfer', 'Transfers'), ('trip', 'Trips'), ('rental', 'Rentals')], default='all', max_length=20, verbose_name='applicable to')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='coupon discount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.coupon', verbose_name='coupon'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='customer email')),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='discount applied')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='used at')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='payments.coupon', verbose_name='coupon')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='payments.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'coupon usage',
                'verbose_name_plural': 'coupon usages',
                'ordering': ['-used_at'],
            },
        ),
    ]
