# Generated by Django 6.0.1 on 2026-01-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='description')),
                ('color', models.CharField(default='#3498db', help_text='Hex color for map display', max_length=7, verbose_name='color')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'zone',
                'verbose_name_plural': 'zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('location_type', models.CharField(choices=[('airport', 'Airport'), ('city', 'City'), ('port', 'Port'), ('hotel', 'Hotel'), ('station', 'Train/Bus Station'), ('address', 'Custom Address')], default='address', max_length=20, verbose_name='type')),
                ('code', models.CharField(blank=True, help_text='Airport/Port code (e.g., CMN, RAK)', max_length=10, verbose_name='code')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='region/state')),
                ('country', models.CharField(default='Morocco', max_length=100, verbose_name='country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude')),
                ('is_popular', models.BooleanField(default=False, verbose_name='popular destination')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='locations.zone', verbose_name='zone')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='distance (km)')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='estimated duration (minutes)')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for economy vehicle', max_digits=10, verbose_name='base price')),
                ('is_popular', models.BooleanField(default=False, verbose_name='popular route')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='locations.location', verbose_name='destination')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='locations.location', verbose_name='origin')),
            ],
            options={
                'verbose_name': 'route',
                'verbose_name_plural': 'routes',
                'ordering': ['origin__name', 'destination__name'],
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='ZonePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('from_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_from', to='locations.zone', verbose_name='from zone')),
                ('to_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_to', to='locations.zone', verbose_name='to zone')),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_pricing', to='vehicles.vehiclecategory', verbose_name='vehicle category')),
            ],
            options={
                'verbose_name': 'zone pricing',
                'verbose_name_plural': 'zone pricing',
                'unique_together': {('from_zone', 'to_zone', 'vehicle_category')},
            },
        ),
    ]
