# Generated by Django 6.0.1 on 2026-01-10 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='center_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude of zone center point', max_digits=10, null=True, verbose_name='center latitude'),
        ),
        migrations.AddField(
            model_name='zone',
            name='center_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude of zone center point', max_digits=10, null=True, verbose_name='center longitude'),
        ),
        migrations.AddField(
            model_name='zone',
            name='polygon_coordinates',
            field=models.JSONField(blank=True, help_text='GeoJSON polygon coordinates defining zone boundary', null=True, verbose_name='polygon coordinates'),
        ),
        migrations.CreateModel(
            name='ZoneDistanceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Short distance", "Medium distance", "Long distance"', max_length=100, verbose_name='range name')),
                ('min_km', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='minimum distance (km)')),
                ('max_km', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='maximum distance (km)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_ranges', to='locations.zone', verbose_name='zone')),
            ],
            options={
                'verbose_name': 'zone distance range',
                'verbose_name_plural': 'zone distance ranges',
                'ordering': ['zone', 'min_km'],
            },
        ),
    ]
