# Generated by Django 6.0.1 on 2026-01-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_zone_geolocation_and_distance_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='radius_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, help_text='Radius of the zone in kilometers', max_digits=8, null=True, verbose_name='radius (km)'),
        ),
    ]
