# Generated by Django 6.0.1 on 2026-01-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_zone_radius_km'),
        ('rentals', '0002_alter_rental_pickup_location_and_more'),
        ('transfers', '0002_remove_transfer_dropoff_location_and_more'),
        ('trips', '0002_remove_tripbooking_pickup_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
