# Generated by Django 6.0.1 on 2026-01-10 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_route_origin_remove_route_destination_and_more'),
        ('vehicles', '0004_vehicle_zone_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Marrakech to Casablanca"', max_length=200, verbose_name='route name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('origin_name', models.CharField(help_text='Origin city or location name', max_length=200, verbose_name='origin')),
                ('origin_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='origin latitude')),
                ('origin_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='origin longitude')),
                ('destination_name', models.CharField(help_text='Destination city or location name', max_length=200, verbose_name='destination')),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='destination latitude')),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='destination longitude')),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Approximate distance in kilometers', max_digits=8, verbose_name='distance (km)')),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated travel time in minutes', null=True, verbose_name='estimated duration (minutes)')),
                ('is_bidirectional', models.BooleanField(default=True, help_text='If true, the same pricing applies for reverse direction', verbose_name='bidirectional')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_popular', models.BooleanField(default=False, help_text='Show this route prominently on the website', verbose_name='popular route')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'route',
                'verbose_name_plural': 'routes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleRoutePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Fixed price for this vehicle on this route', max_digits=10, verbose_name='price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_pricing', to='locations.route', verbose_name='route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_pricing', to='vehicles.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'vehicle route pricing',
                'verbose_name_plural': 'vehicle route pricing',
                'ordering': ['vehicle', 'route'],
                'unique_together': {('vehicle', 'route')},
            },
        ),
    ]
