# Generated by Django 6.0.1 on 2026-01-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination_radius_km',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Dropoff area radius in kilometers', max_digits=6, verbose_name='destination radius (km)'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_radius_km',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Pickup area radius in kilometers', max_digits=6, verbose_name='origin radius (km)'),
        ),
    ]
