# Generated by Django 5.0.1 on 2026-01-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_add_route_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleroutepricing',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost from supplier for this route', max_digits=10, null=True, verbose_name='cost'),
        ),
    ]
