# Generated by Django 5.0.1 on 2026-01-28 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_add_cost_field'),
        ('vehicles', '0008_add_cost_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleroutepricing',
            options={'ordering': ['vehicle', 'route', 'pickup_zone', 'dropoff_zone'], 'verbose_name': 'vehicle route pricing', 'verbose_name_plural': 'vehicle route pricing'},
        ),
        migrations.AlterUniqueTogether(
            name='vehicleroutepricing',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vehicleroutepricing',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost from supplier for this route/zone combination', max_digits=10, null=True, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='vehicleroutepricing',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Fixed price for this vehicle on this route/zone combination', max_digits=10, verbose_name='price'),
        ),
        migrations.CreateModel(
            name='RouteDropoffZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Hotel Area"', max_length=200, verbose_name='zone name')),
                ('center_latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='center latitude')),
                ('center_longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='center longitude')),
                ('radius_km', models.DecimalField(decimal_places=2, default=5, help_text='Dropoff area radius in kilometers', max_digits=6, verbose_name='radius (km)')),
                ('color', models.CharField(default='#dc3545', help_text='Hex color for map display', max_length=7, verbose_name='color')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_zones', to='locations.route', verbose_name='route')),
            ],
            options={
                'verbose_name': 'route dropoff zone',
                'verbose_name_plural': 'route dropoff zones',
                'ordering': ['route', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='vehicleroutepricing',
            name='dropoff_zone',
            field=models.ForeignKey(blank=True, help_text='Leave empty for route-wide default pricing', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='locations.routedropoffzone', verbose_name='dropoff zone'),
        ),
        migrations.CreateModel(
            name='RoutePickupZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Medina"', max_length=200, verbose_name='zone name')),
                ('center_latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='center latitude')),
                ('center_longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='center longitude')),
                ('radius_km', models.DecimalField(decimal_places=2, default=5, help_text='Pickup area radius in kilometers', max_digits=6, verbose_name='radius (km)')),
                ('color', models.CharField(default='#28a745', help_text='Hex color for map display', max_length=7, verbose_name='color')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_zones', to='locations.route', verbose_name='route')),
            ],
            options={
                'verbose_name': 'route pickup zone',
                'verbose_name_plural': 'route pickup zones',
                'ordering': ['route', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='vehicleroutepricing',
            name='pickup_zone',
            field=models.ForeignKey(blank=True, help_text='Leave empty for route-wide default pricing', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='locations.routepickupzone', verbose_name='pickup zone'),
        ),
        migrations.AddConstraint(
            model_name='vehicleroutepricing',
            constraint=models.UniqueConstraint(fields=('vehicle', 'route', 'pickup_zone', 'dropoff_zone'), name='unique_vehicle_route_zone_pricing'),
        ),
    ]
