# Generated by Django 5.0.1 on 2026-01-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_route_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleroutepricing',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deposit amount required for booking', max_digits=10, null=True, verbose_name='deposit'),
        ),
        migrations.AddField(
            model_name='vehicleroutepricing',
            name='min_booking_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum hours in advance required to book', null=True, verbose_name='minimum booking hours'),
        ),
    ]
