# Generated by Django 6.0.1 on 2026-02-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_add_deposit_and_booking_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='deposit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of total price required as deposit (0-100)', max_digits=5, verbose_name='deposit percentage'),
        ),
        migrations.AddField(
            model_name='zone',
            name='deposit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of total price required as deposit (0-100)', max_digits=5, verbose_name='deposit percentage'),
        ),
    ]
