# Generated by Django 5.0.1 on 2026-02-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_route_deposit_percentage_zone_deposit_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='custom_info',
            field=models.JSONField(blank=True, default=dict, help_text='Custom key-value data for this route', verbose_name='custom information'),
        ),
        migrations.AddField(
            model_name='zone',
            name='custom_info',
            field=models.JSONField(blank=True, default=dict, help_text='Custom key-value data for this zone', verbose_name='custom information'),
        ),
    ]
