# Generated by Django 5.0.1 on 2026-02-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_route_custom_info_zone_custom_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'zone', 'verbose_name_plural': 'zones'},
        ),
        migrations.AddField(
            model_name='route',
            name='cancellation_policy_override',
            field=models.TextField(blank=True, help_text='Override cancellation policy for this route', verbose_name='cancellation policy'),
        ),
        migrations.AddField(
            model_name='route',
            name='cancellation_policy_override_ar',
            field=models.TextField(blank=True, help_text='Override cancellation policy for this route', null=True, verbose_name='cancellation policy'),
        ),
        migrations.AddField(
            model_name='route',
            name='cancellation_policy_override_de',
            field=models.TextField(blank=True, help_text='Override cancellation policy for this route', null=True, verbose_name='cancellation policy'),
        ),
        migrations.AddField(
            model_name='route',
            name='cancellation_policy_override_en',
            field=models.TextField(blank=True, help_text='Override cancellation policy for this route', null=True, verbose_name='cancellation policy'),
        ),
        migrations.AddField(
            model_name='route',
            name='cancellation_policy_override_es',
            field=models.TextField(blank=True, help_text='Override cancellation policy for this route', null=True, verbose_name='cancellation policy'),
        ),
        migrations.AddField(
            model_name='route',
            name='cancellation_policy_override_fr',
            field=models.TextField(blank=True, help_text='Override cancellation policy for this route', null=True, verbose_name='cancellation policy'),
        ),
        migrations.AddField(
            model_name='route',
            name='cancellation_policy_override_it',
            field=models.TextField(blank=True, help_text='Override cancellation policy for this route', null=True, verbose_name='cancellation policy'),
        ),
        migrations.AddField(
            model_name='route',
            name='cancellation_policy_override_pt',
            field=models.TextField(blank=True, help_text='Override cancellation policy for this route', null=True, verbose_name='cancellation policy'),
        ),
        migrations.AddField(
            model_name='route',
            name='client_notice',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this route', verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='route',
            name='client_notice_ar',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this route', null=True, verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='route',
            name='client_notice_de',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this route', null=True, verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='route',
            name='client_notice_en',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this route', null=True, verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='route',
            name='client_notice_es',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this route', null=True, verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='route',
            name='client_notice_fr',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this route', null=True, verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='route',
            name='client_notice_it',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this route', null=True, verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='route',
            name='client_notice_pt',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this route', null=True, verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='route',
            name='client_notice_type',
            field=models.CharField(blank=True, choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success')], default='info', max_length=20, verbose_name='notice type'),
        ),
        migrations.AddField(
            model_name='route',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='route',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='route',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='route',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='route',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='route',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='route',
            name='description_pt',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination_name_ar',
            field=models.CharField(help_text='Destination city or location name', max_length=200, null=True, verbose_name='destination'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination_name_de',
            field=models.CharField(help_text='Destination city or location name', max_length=200, null=True, verbose_name='destination'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination_name_en',
            field=models.CharField(help_text='Destination city or location name', max_length=200, null=True, verbose_name='destination'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination_name_es',
            field=models.CharField(help_text='Destination city or location name', max_length=200, null=True, verbose_name='destination'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination_name_fr',
            field=models.CharField(help_text='Destination city or location name', max_length=200, null=True, verbose_name='destination'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination_name_it',
            field=models.CharField(help_text='Destination city or location name', max_length=200, null=True, verbose_name='destination'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination_name_pt',
            field=models.CharField(help_text='Destination city or location name', max_length=200, null=True, verbose_name='destination'),
        ),
        migrations.AddField(
            model_name='route',
            name='estimated_traffic_info',
            field=models.TextField(blank=True, help_text='Estimated traffic information', verbose_name='traffic info'),
        ),
        migrations.AddField(
            model_name='route',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='List of highlight strings', verbose_name='highlights'),
        ),
        migrations.AddField(
            model_name='route',
            name='included_amenities',
            field=models.JSONField(blank=True, default=list, help_text='List of included amenity strings', verbose_name='included amenities'),
        ),
        migrations.AddField(
            model_name='route',
            name='name_ar',
            field=models.CharField(help_text='e.g., "Marrakech to Casablanca"', max_length=200, null=True, verbose_name='route name'),
        ),
        migrations.AddField(
            model_name='route',
            name='name_de',
            field=models.CharField(help_text='e.g., "Marrakech to Casablanca"', max_length=200, null=True, verbose_name='route name'),
        ),
        migrations.AddField(
            model_name='route',
            name='name_en',
            field=models.CharField(help_text='e.g., "Marrakech to Casablanca"', max_length=200, null=True, verbose_name='route name'),
        ),
        migrations.AddField(
            model_name='route',
            name='name_es',
            field=models.CharField(help_text='e.g., "Marrakech to Casablanca"', max_length=200, null=True, verbose_name='route name'),
        ),
        migrations.AddField(
            model_name='route',
            name='name_fr',
            field=models.CharField(help_text='e.g., "Marrakech to Casablanca"', max_length=200, null=True, verbose_name='route name'),
        ),
        migrations.AddField(
            model_name='route',
            name='name_it',
            field=models.CharField(help_text='e.g., "Marrakech to Casablanca"', max_length=200, null=True, verbose_name='route name'),
        ),
        migrations.AddField(
            model_name='route',
            name='name_pt',
            field=models.CharField(help_text='e.g., "Marrakech to Casablanca"', max_length=200, null=True, verbose_name='route name'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_name_ar',
            field=models.CharField(help_text='Origin city or location name', max_length=200, null=True, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_name_de',
            field=models.CharField(help_text='Origin city or location name', max_length=200, null=True, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_name_en',
            field=models.CharField(help_text='Origin city or location name', max_length=200, null=True, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_name_es',
            field=models.CharField(help_text='Origin city or location name', max_length=200, null=True, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_name_fr',
            field=models.CharField(help_text='Origin city or location name', max_length=200, null=True, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_name_it',
            field=models.CharField(help_text='Origin city or location name', max_length=200, null=True, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_name_pt',
            field=models.CharField(help_text='Origin city or location name', max_length=200, null=True, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_description',
            field=models.TextField(blank=True, help_text='Detailed customer-facing route description', verbose_name='route description'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_description_ar',
            field=models.TextField(blank=True, help_text='Detailed customer-facing route description', null=True, verbose_name='route description'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_description_de',
            field=models.TextField(blank=True, help_text='Detailed customer-facing route description', null=True, verbose_name='route description'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_description_en',
            field=models.TextField(blank=True, help_text='Detailed customer-facing route description', null=True, verbose_name='route description'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_description_es',
            field=models.TextField(blank=True, help_text='Detailed customer-facing route description', null=True, verbose_name='route description'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_description_fr',
            field=models.TextField(blank=True, help_text='Detailed customer-facing route description', null=True, verbose_name='route description'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_description_it',
            field=models.TextField(blank=True, help_text='Detailed customer-facing route description', null=True, verbose_name='route description'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_description_pt',
            field=models.TextField(blank=True, help_text='Detailed customer-facing route description', null=True, verbose_name='route description'),
        ),
        migrations.AddField(
            model_name='route',
            name='travel_tips',
            field=models.TextField(blank=True, help_text='Travel tips for customers', verbose_name='travel tips'),
        ),
        migrations.AddField(
            model_name='route',
            name='travel_tips_ar',
            field=models.TextField(blank=True, help_text='Travel tips for customers', null=True, verbose_name='travel tips'),
        ),
        migrations.AddField(
            model_name='route',
            name='travel_tips_de',
            field=models.TextField(blank=True, help_text='Travel tips for customers', null=True, verbose_name='travel tips'),
        ),
        migrations.AddField(
            model_name='route',
            name='travel_tips_en',
            field=models.TextField(blank=True, help_text='Travel tips for customers', null=True, verbose_name='travel tips'),
        ),
        migrations.AddField(
            model_name='route',
            name='travel_tips_es',
            field=models.TextField(blank=True, help_text='Travel tips for customers', null=True, verbose_name='travel tips'),
        ),
        migrations.AddField(
            model_name='route',
            name='travel_tips_fr',
            field=models.TextField(blank=True, help_text='Travel tips for customers', null=True, verbose_name='travel tips'),
        ),
        migrations.AddField(
            model_name='route',
            name='travel_tips_it',
            field=models.TextField(blank=True, help_text='Travel tips for customers', null=True, verbose_name='travel tips'),
        ),
        migrations.AddField(
            model_name='route',
            name='travel_tips_pt',
            field=models.TextField(blank=True, help_text='Travel tips for customers', null=True, verbose_name='travel tips'),
        ),
        migrations.AddField(
            model_name='routedropoffzone',
            name='name_ar',
            field=models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Hotel Area"', max_length=200, null=True, verbose_name='zone name'),
        ),
        migrations.AddField(
            model_name='routedropoffzone',
            name='name_de',
            field=models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Hotel Area"', max_length=200, null=True, verbose_name='zone name'),
        ),
        migrations.AddField(
            model_name='routedropoffzone',
            name='name_en',
            field=models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Hotel Area"', max_length=200, null=True, verbose_name='zone name'),
        ),
        migrations.AddField(
            model_name='routedropoffzone',
            name='name_es',
            field=models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Hotel Area"', max_length=200, null=True, verbose_name='zone name'),
        ),
        migrations.AddField(
            model_name='routedropoffzone',
            name='name_fr',
            field=models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Hotel Area"', max_length=200, null=True, verbose_name='zone name'),
        ),
        migrations.AddField(
            model_name='routedropoffzone',
            name='name_it',
            field=models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Hotel Area"', max_length=200, null=True, verbose_name='zone name'),
        ),
        migrations.AddField(
            model_name='routedropoffzone',
            name='name_pt',
            field=models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Hotel Area"', max_length=200, null=True, verbose_name='zone name'),
        ),
        migrations.AddField(
            model_name='routepickupzone',
            name='name_ar',
            field=models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Medina"', max_length=200, null=True, verbose_name='zone name'),
        ),
        migrations.AddField(
            model_name='routepickupzone',
            name='name_de',
            field=models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Medina"', max_length=200, null=True, verbose_name='zone name'),
        ),
        migrations.AddField(
            model_name='routepickupzone',
            name='name_en',
            field=models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Medina"', max_length=200, null=True, verbose_name='zone name'),
        ),
        migrations.AddField(
            model_name='routepickupzone',
            name='name_es',
            field=models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Medina"', max_length=200, null=True, verbose_name='zone name'),
        ),
        migrations.AddField(
            model_name='routepickupzone',
            name='name_fr',
            field=models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Medina"', max_length=200, null=True, verbose_name='zone name'),
        ),
        migrations.AddField(
            model_name='routepickupzone',
            name='name_it',
            field=models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Medina"', max_length=200, null=True, verbose_name='zone name'),
        ),
        migrations.AddField(
            model_name='routepickupzone',
            name='name_pt',
            field=models.CharField(help_text='e.g., "Airport Terminal", "City Center", "Medina"', max_length=200, null=True, verbose_name='zone name'),
        ),
        migrations.AddField(
            model_name='zone',
            name='area_description',
            field=models.TextField(blank=True, help_text='Description of the area for customers', verbose_name='area description'),
        ),
        migrations.AddField(
            model_name='zone',
            name='area_description_ar',
            field=models.TextField(blank=True, help_text='Description of the area for customers', null=True, verbose_name='area description'),
        ),
        migrations.AddField(
            model_name='zone',
            name='area_description_de',
            field=models.TextField(blank=True, help_text='Description of the area for customers', null=True, verbose_name='area description'),
        ),
        migrations.AddField(
            model_name='zone',
            name='area_description_en',
            field=models.TextField(blank=True, help_text='Description of the area for customers', null=True, verbose_name='area description'),
        ),
        migrations.AddField(
            model_name='zone',
            name='area_description_es',
            field=models.TextField(blank=True, help_text='Description of the area for customers', null=True, verbose_name='area description'),
        ),
        migrations.AddField(
            model_name='zone',
            name='area_description_fr',
            field=models.TextField(blank=True, help_text='Description of the area for customers', null=True, verbose_name='area description'),
        ),
        migrations.AddField(
            model_name='zone',
            name='area_description_it',
            field=models.TextField(blank=True, help_text='Description of the area for customers', null=True, verbose_name='area description'),
        ),
        migrations.AddField(
            model_name='zone',
            name='area_description_pt',
            field=models.TextField(blank=True, help_text='Description of the area for customers', null=True, verbose_name='area description'),
        ),
        migrations.AddField(
            model_name='zone',
            name='client_notice',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this zone', verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='zone',
            name='client_notice_ar',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this zone', null=True, verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='zone',
            name='client_notice_de',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this zone', null=True, verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='zone',
            name='client_notice_en',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this zone', null=True, verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='zone',
            name='client_notice_es',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this zone', null=True, verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='zone',
            name='client_notice_fr',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this zone', null=True, verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='zone',
            name='client_notice_it',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this zone', null=True, verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='zone',
            name='client_notice_pt',
            field=models.TextField(blank=True, help_text='Notice shown to customers for this zone', null=True, verbose_name='client notice'),
        ),
        migrations.AddField(
            model_name='zone',
            name='client_notice_type',
            field=models.CharField(blank=True, choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success')], default='info', max_length=20, verbose_name='notice type'),
        ),
        migrations.AddField(
            model_name='zone',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='zone',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='zone',
            name='description_pt',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='zone',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='display order'),
        ),
        migrations.AddField(
            model_name='zone',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='zone',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='zone',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='zone',
            name='pickup_instructions',
            field=models.TextField(blank=True, help_text='Pickup instructions for customers', verbose_name='pickup instructions'),
        ),
        migrations.AddField(
            model_name='zone',
            name='pickup_instructions_ar',
            field=models.TextField(blank=True, help_text='Pickup instructions for customers', null=True, verbose_name='pickup instructions'),
        ),
        migrations.AddField(
            model_name='zone',
            name='pickup_instructions_de',
            field=models.TextField(blank=True, help_text='Pickup instructions for customers', null=True, verbose_name='pickup instructions'),
        ),
        migrations.AddField(
            model_name='zone',
            name='pickup_instructions_en',
            field=models.TextField(blank=True, help_text='Pickup instructions for customers', null=True, verbose_name='pickup instructions'),
        ),
        migrations.AddField(
            model_name='zone',
            name='pickup_instructions_es',
            field=models.TextField(blank=True, help_text='Pickup instructions for customers', null=True, verbose_name='pickup instructions'),
        ),
        migrations.AddField(
            model_name='zone',
            name='pickup_instructions_fr',
            field=models.TextField(blank=True, help_text='Pickup instructions for customers', null=True, verbose_name='pickup instructions'),
        ),
        migrations.AddField(
            model_name='zone',
            name='pickup_instructions_it',
            field=models.TextField(blank=True, help_text='Pickup instructions for customers', null=True, verbose_name='pickup instructions'),
        ),
        migrations.AddField(
            model_name='zone',
            name='pickup_instructions_pt',
            field=models.TextField(blank=True, help_text='Pickup instructions for customers', null=True, verbose_name='pickup instructions'),
        ),
    ]
