# Generated by Django 6.0.1 on 2026-01-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='description')),
                ('max_passengers', models.PositiveSmallIntegerField(default=4, verbose_name='max passengers')),
                ('max_luggage', models.PositiveSmallIntegerField(default=3, verbose_name='max luggage')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier applied to base route price', max_digits=4, verbose_name='price multiplier')),
                ('icon', models.CharField(blank=True, help_text='CSS icon class or icon name', max_length=50, verbose_name='icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_categories/', verbose_name='image')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'vehicle category',
                'verbose_name_plural': 'vehicle categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'vehicle feature',
                'verbose_name_plural': 'vehicle features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Mercedes E-Class', max_length=100, verbose_name='name')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='license plate')),
                ('year', models.PositiveSmallIntegerField(verbose_name='year')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='color')),
                ('passengers', models.PositiveSmallIntegerField(verbose_name='passenger capacity')),
                ('luggage', models.PositiveSmallIntegerField(verbose_name='luggage capacity')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='daily rental rate')),
                ('weekly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='weekly rental rate')),
                ('is_available_for_rental', models.BooleanField(default=False, verbose_name='available for rental')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.vehiclecategory', verbose_name='category')),
                ('features', models.ManyToManyField(blank=True, related_name='vehicles', to='vehicles.vehiclefeature', verbose_name='features')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary image')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'vehicle image',
                'verbose_name_plural': 'vehicle images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
