# Generated by Django 6.0.1 on 2026-01-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_route_origin_remove_route_destination_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategoryZonePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Fixed price for this category in this distance range', max_digits=10, verbose_name='price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_range_pricing', to='vehicles.vehiclecategory', verbose_name='vehicle category')),
                ('zone_distance_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_pricing', to='locations.zonedistancerange', verbose_name='zone distance range')),
            ],
            options={
                'verbose_name': 'vehicle category zone pricing',
                'verbose_name_plural': 'vehicle category zone pricing',
                'ordering': ['vehicle_category', 'zone_distance_range'],
                'unique_together': {('vehicle_category', 'zone_distance_range')},
            },
        ),
    ]
