# Generated by Django 6.0.1 on 2026-01-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclecategoryzonepricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_available_for_rental',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_type',
            field=models.CharField(choices=[('transfer', 'Transfer Only'), ('rental', 'Rental Only'), ('both', 'Both Transfer & Rental')], default='transfer', help_text='What service this vehicle is available for', max_length=20, verbose_name='service type'),
        ),
    ]
