# Generated by Django 6.0.1 on 2026-01-10 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_route_origin_remove_route_destination_and_more'),
        ('vehicles', '0003_add_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='service_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('rental', 'Rental')], default='transfer', help_text='What service this vehicle is available for', max_length=20, verbose_name='service type'),
        ),
        migrations.CreateModel(
            name='VehicleZonePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Fixed price for this vehicle in this distance range', max_digits=10, verbose_name='price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_pricing', to='vehicles.vehicle', verbose_name='vehicle')),
                ('zone_distance_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_pricing', to='locations.zonedistancerange', verbose_name='zone distance range')),
            ],
            options={
                'verbose_name': 'vehicle zone pricing',
                'verbose_name_plural': 'vehicle zone pricing',
                'ordering': ['vehicle', 'zone_distance_range'],
                'unique_together': {('vehicle', 'zone_distance_range')},
            },
        ),
        migrations.DeleteModel(
            name='VehicleCategoryZonePricing',
        ),
    ]
