# Generated by Django 5.0.1 on 2026-01-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_remove_required_vehicle_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost from supplier', max_digits=10, null=True, verbose_name='cost'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='supplier name'),
        ),
    ]
