# Generated by Django 5.0.1 on 2026-01-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_add_supplier_and_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='cost',
        ),
    ]
