# Generated by Django 5.0.1 on 2026-02-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_add_deposit_and_booking_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='custom_info',
            field=models.JSONField(blank=True, default=dict, help_text='Custom key-value data for this vehicle', verbose_name='custom information'),
        ),
    ]
