# Generated by Django 5.0.1 on 2026-02-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehicle_custom_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='client_description',
            field=models.TextField(blank=True, help_text='Customer-facing vehicle description', verbose_name='client description'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='client_description_ar',
            field=models.TextField(blank=True, help_text='Customer-facing vehicle description', null=True, verbose_name='client description'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='client_description_de',
            field=models.TextField(blank=True, help_text='Customer-facing vehicle description', null=True, verbose_name='client description'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='client_description_en',
            field=models.TextField(blank=True, help_text='Customer-facing vehicle description', null=True, verbose_name='client description'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='client_description_es',
            field=models.TextField(blank=True, help_text='Customer-facing vehicle description', null=True, verbose_name='client description'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='client_description_fr',
            field=models.TextField(blank=True, help_text='Customer-facing vehicle description', null=True, verbose_name='client description'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='client_description_it',
            field=models.TextField(blank=True, help_text='Customer-facing vehicle description', null=True, verbose_name='client description'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='client_description_pt',
            field=models.TextField(blank=True, help_text='Customer-facing vehicle description', null=True, verbose_name='client description'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='important_note',
            field=models.TextField(blank=True, help_text='Important note shown to customers', verbose_name='important note'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='important_note_ar',
            field=models.TextField(blank=True, help_text='Important note shown to customers', null=True, verbose_name='important note'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='important_note_de',
            field=models.TextField(blank=True, help_text='Important note shown to customers', null=True, verbose_name='important note'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='important_note_en',
            field=models.TextField(blank=True, help_text='Important note shown to customers', null=True, verbose_name='important note'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='important_note_es',
            field=models.TextField(blank=True, help_text='Important note shown to customers', null=True, verbose_name='important note'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='important_note_fr',
            field=models.TextField(blank=True, help_text='Important note shown to customers', null=True, verbose_name='important note'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='important_note_it',
            field=models.TextField(blank=True, help_text='Important note shown to customers', null=True, verbose_name='important note'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='important_note_pt',
            field=models.TextField(blank=True, help_text='Important note shown to customers', null=True, verbose_name='important note'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='important_note_type',
            field=models.CharField(blank=True, choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success')], default='info', max_length=20, verbose_name='note type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='key_features',
            field=models.JSONField(blank=True, default=list, help_text='List of key feature strings', verbose_name='key features'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_ar',
            field=models.CharField(help_text='e.g., Mercedes E-Class', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_de',
            field=models.CharField(help_text='e.g., Mercedes E-Class', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_en',
            field=models.CharField(help_text='e.g., Mercedes E-Class', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_es',
            field=models.CharField(help_text='e.g., Mercedes E-Class', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_fr',
            field=models.CharField(help_text='e.g., Mercedes E-Class', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_it',
            field=models.CharField(help_text='e.g., Mercedes E-Class', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_pt',
            field=models.CharField(help_text='e.g., Mercedes E-Class', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='description_pt',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='included_amenities',
            field=models.JSONField(blank=True, default=list, help_text='List of included amenity strings', verbose_name='included amenities'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='not_included',
            field=models.JSONField(blank=True, default=list, help_text='List of items not included', verbose_name='not included'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short tagline shown on results page', max_length=200, verbose_name='tagline'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='tagline_ar',
            field=models.CharField(blank=True, help_text='Short tagline shown on results page', max_length=200, null=True, verbose_name='tagline'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='tagline_de',
            field=models.CharField(blank=True, help_text='Short tagline shown on results page', max_length=200, null=True, verbose_name='tagline'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='tagline_en',
            field=models.CharField(blank=True, help_text='Short tagline shown on results page', max_length=200, null=True, verbose_name='tagline'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='tagline_es',
            field=models.CharField(blank=True, help_text='Short tagline shown on results page', max_length=200, null=True, verbose_name='tagline'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='tagline_fr',
            field=models.CharField(blank=True, help_text='Short tagline shown on results page', max_length=200, null=True, verbose_name='tagline'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='tagline_it',
            field=models.CharField(blank=True, help_text='Short tagline shown on results page', max_length=200, null=True, verbose_name='tagline'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='tagline_pt',
            field=models.CharField(blank=True, help_text='Short tagline shown on results page', max_length=200, null=True, verbose_name='tagline'),
        ),
        migrations.AddField(
            model_name='vehiclefeature',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='vehiclefeature',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='vehiclefeature',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='caption_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='caption_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='caption_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='caption_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='caption_it',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='caption_pt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='caption'),
        ),
    ]
