# Generated by Django 5.0.1 on 2026-02-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_vehicle_company_vehicle_doors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='supplier email'),
        ),
    ]
